// This model was generated by Lumber. However, you remain in control of your models.

// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Account = sequelize.define(
    "account",
    {
      id: {
        type: DataTypes.UUID,
        primaryKey: true,
        defaultValue: Sequelize.literal("uuid_generate_v4()"),
        allowNull: false,
      },
      createdAt: {
        type: DataTypes.DATE,
      },
      updatedAt: {
        type: DataTypes.DATE,
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      alarisUsername: {
        type: DataTypes.STRING,
        defaultValue: "",
      },
      alarisPassword: {
        type: DataTypes.STRING,
        defaultValue: "",
      },
      alarisUrl: {
        type: DataTypes.STRING,
        defaultValue: "",
      },
    },
    {
      tableName: "account",
      underscored: true,
      schema: process.env.DATABASE_SCHEMA,
    }
  );

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Account.associate = (models) => {
    Account.hasMany(models.accountApiKeys, {
      foreignKey: {
        name: "accountIdKey",
        field: "account_id",
      },
      as: "accountApiKeys",
    });  
  };


  return Account;
};
