apiVersion: v1
clusters:
  - cluster:
      server: https://AEC53857DCB2A9B0022C4C14347279BD.gr7.ap-southeast-2.eks.amazonaws.com
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1ESXdOakEwTkRZek5Wb1hEVE14TURJd05EQTBORFl6TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUGpICkNBdkRPb3g1ajRQWWEwODJXN2JDR3B1dmlFTGh1eDRrTTFkOW5qbEphUFRDNmhONk5jblZvWG8rK0luNUhFK1EKeG45THdqNU1wSndMNHhHU2JpZEwwUnpFK1JmUGh2MHRYVFhRMExWSWhEd2luL2xyYWM1SU9rdkJjMFBKSFFabAorR0FNbnZhaVpXOWJ4RnlBbW45Q3loNTdTN3lpK2pOaFdlOVpSL001N0I2OTRpSENCbllJeWpZUUtJR3FQREJFClBkc3ZwUVZ3ak13bkVFRzVwemJNMWV6ekQ2TGRualhiUVd2WmJsUzB6ampVNytxVEExWHhHdlVqY0p5SGY0dVYKOEpreHZOc0o3RWMvT2t2eG14aFE0YURMM3ZWOGZXQWMzRXZldFFMckd1SVNIdGxjMGdCK25WR3YvbXppcU5rMApuV1pMeEFOdXlsbHBWcjM1NHFzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFML3F6T2pURmJPK1RWcHJ2bjZCVkQ4VVNHZkQKTHhDbFFlVVVVNDJXU2RCUVdwNEIzZzVuY0wvSm5ONktkZWI5S3hrUm1jVSt3dzJwaURLZ0tVUkFxK0kyODFUMQppdng4Rll0ME85VnhLaStZWU1wcWxlNHBnTlUrdVJqWEgzbC8xeTh1OW56TjdJKzNoclIwdGtBTnV1S1hRMGdCCnpqRVM4WFRadWt3VzBRb1c1MGZwTS9kSW1OQUtxV2VHN3ptVEhZbklaSTBmTnE2K1lFYjFQeTBZUjlyeGNRcXEKTzUxVnU5YzhQaktaSlk1SHlqeUZOTHpHUGorYzlCZFZqaTJ2SVp5L0c1aFlFR3B2a3VjdzlhWjZ6ZzJITERPUApLbWhobURXQzJwRElTcElNK1huTWFsVnNXLzkrdjFqU3RUZlp0ZFNyTzNhSTdBS3Jxc21qZ2FXTmQyRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      user: aws
    name: aws
current-context: aws
kind: Config
preferences: {}
users:
  - name: aws
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        command: aws-iam-authenticator
        args:
          - "token"
          - "-i"
          - "tp-qa"
        env:
          - name: AWS_PROFILE
            value: "mtmo-non-prod"
