# First stage: Build the executable
FROM golang:alpine

ENV GO111MODULE on
ENV DISABLE_NEW_RELIC true

RUN apk update && apk add git
RUN go get -u github.com/cortesi/modd/cmd/modd

WORKDIR /backend

CMD /go/bin/modd --file="./webhook/rpc/modd.conf"
