# The subchart contains default values which can be overridden here
k8sDeploymentJobChart:
  name: optout-migration-job
  # Component is the group of services (domain) the service belongs to
  component: sms
  namespace: tp
  # Harness can create a namespace if not exists so this is set to true in Harness.
  # Helm install will error if the namespace already exists so set this to false
  # and create the namespace first in deploy_services.sh when manually deploying.
  createNamespace: ${environmentVariable.createNamespace}
  replicas: 1

  image:
    repository: 006764518182.dkr.ecr.ap-southeast-2.amazonaws.com
    tag: ${artifact.buildNo}

  podLabels:
    # env label required for New Relic integration
    env: ${env.name}

  # WORKAROUND: Till https://www.pivotaltracker.com/story/show/174031674 is implemented
  podAnnotations:
    linkerd.io/inject: disabled

  restartPolicy: Never

  job:
    command:
      - /app
    #parallelism: 
    #args:

  # post-install what defines this resource as a hook. Without this line, the
  # job is considered part of the release.
  jobAnnotations:
    hook: post-install
    hook-weight: "-5"
    hook-delete-policy: hook-succeeded

  # Specify all environment variables to be added to the container.
  env:
    config:
      NR_NAME: "${env.name}"
      NR_LICENSE: "3289b893db560c39096d3c222d4a33037c24f943"
      NR_TRACING: "true"
      POSTGRES_NAME: "optout"
      POSTGRES_USER: "foo"
      POSTGRES_AUTH_DB: "sendsei"
      POSTGRES_SSL: "require"
    secrets:
      POSTGRES_PASSWORD: "barbut8chars"
