deployment:
  replicas: 3

resources:
  requests:
    cpu: "250m"
    memory: "300Mi"
  limits:
    cpu: "500m"
    memory: "750Mi"

service:
  annotations:
    "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
  spec:
    externalTrafficPolicy: Local

ports:
  web:
    port: 80
  websecure:
    port: 443

additionalArguments:
  - "--providers.kubernetesIngress.ingressClass=traefik"
  - "--providers.kubernetesingress.ingressendpoint.hostname=${environment_name}"
  - "--providers.kubernetesingress.ingressendpoint.publishedservice=traefik/traefik"
  - "--entrypoints.web.address=:80"
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
  - "--entrypoints.websecure.address=:443"
  - "--entrypoints.websecure.http.tls"

# Need this due to an issue with Traefik redirects
# https://github.com/traefik/traefik-helm-chart/issues/336
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
