FROM ubuntu:precise

RUN apt-get update && apt-get install -y \
    bison \
    build-essential \
    libxml2-dev \
    libssl-dev \
    libmysqlclient-dev \
    libmysql++-dev \
    curl

RUN curl -k https://redmine.kannel.org/attachments/download/322/gateway-1.4.5.tar.gz -o gateway-1.4.5.tar.gz
RUN tar xzf gateway-1.4.5.tar.gz

RUN curl -k -L https://github.com/redis/hiredis/archive/v0.13.3.tar.gz -o hiredis-0.13.3.tar.gz
RUN tar xzf hiredis-0.13.3.tar.gz
WORKDIR /hiredis-0.13.3
RUN make
RUN cp libhiredis.so /usr/lib/libhiredis.so.0.13

WORKDIR /gateway-1.4.5

RUN ./configure --prefix=/usr --sysconfdir=/etc/kannel --with-mysql --with-redis --with-redis-dir=/hiredis-0.13.3 --disable-wap
RUN touch .depend
RUN make
RUN make install

RUN cp test/fakesmsc /usr/sbin/
# RUN rm gateway-1.4.5.tar.gz && rm -Rf gateway-1.4.5

RUN mkdir -p /var/log/kannel && mkdir -p /var/spool/kannel

WORKDIR /usr/sbin
ARG KANNEL_CONFIG
COPY $KANNEL_CONFIG kannel.conf

CMD /usr/sbin/bearerbox -v 1 -d -P /usr/sbin/kannel.conf & \
    sleep 3 && /usr/sbin/smsbox -v 1 -d -P /usr/sbin/kannel.conf & \
  	echo "waiting a sec to start fakesms" & sleep 2 && /usr/sbin/fakesmsc -P -m 1 --logfile /var/log/kannel/fakesmsc.log "123 123 text starting fakesmsc"
