// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package senderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	FindSenderByAddressAndAccountID(ctx context.Context, in *FindSenderByAddressAndAccountIDParams, opts ...grpc.CallOption) (*FindSenderByAddressAndAccountIDReply, error)
	FindSendersByAccountId(ctx context.Context, in *FindSendersByAccountIdParams, opts ...grpc.CallOption) (*FindSendersByAccountIdReply, error)
	FindSendersByAddress(ctx context.Context, in *FindSendersByAddressParams, opts ...grpc.CallOption) (*FindSendersByAddressReply, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) FindSenderByAddressAndAccountID(ctx context.Context, in *FindSenderByAddressAndAccountIDParams, opts ...grpc.CallOption) (*FindSenderByAddressAndAccountIDReply, error) {
	out := new(FindSenderByAddressAndAccountIDReply)
	err := c.cc.Invoke(ctx, "/senderpb.Service/FindSenderByAddressAndAccountID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) FindSendersByAccountId(ctx context.Context, in *FindSendersByAccountIdParams, opts ...grpc.CallOption) (*FindSendersByAccountIdReply, error) {
	out := new(FindSendersByAccountIdReply)
	err := c.cc.Invoke(ctx, "/senderpb.Service/FindSendersByAccountId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) FindSendersByAddress(ctx context.Context, in *FindSendersByAddressParams, opts ...grpc.CallOption) (*FindSendersByAddressReply, error) {
	out := new(FindSendersByAddressReply)
	err := c.cc.Invoke(ctx, "/senderpb.Service/FindSendersByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	FindSenderByAddressAndAccountID(context.Context, *FindSenderByAddressAndAccountIDParams) (*FindSenderByAddressAndAccountIDReply, error)
	FindSendersByAccountId(context.Context, *FindSendersByAccountIdParams) (*FindSendersByAccountIdReply, error)
	FindSendersByAddress(context.Context, *FindSendersByAddressParams) (*FindSendersByAddressReply, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) FindSenderByAddressAndAccountID(context.Context, *FindSenderByAddressAndAccountIDParams) (*FindSenderByAddressAndAccountIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSenderByAddressAndAccountID not implemented")
}
func (UnimplementedServiceServer) FindSendersByAccountId(context.Context, *FindSendersByAccountIdParams) (*FindSendersByAccountIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSendersByAccountId not implemented")
}
func (UnimplementedServiceServer) FindSendersByAddress(context.Context, *FindSendersByAddressParams) (*FindSendersByAddressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSendersByAddress not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_FindSenderByAddressAndAccountID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSenderByAddressAndAccountIDParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).FindSenderByAddressAndAccountID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/senderpb.Service/FindSenderByAddressAndAccountID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).FindSenderByAddressAndAccountID(ctx, req.(*FindSenderByAddressAndAccountIDParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_FindSendersByAccountId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSendersByAccountIdParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).FindSendersByAccountId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/senderpb.Service/FindSendersByAccountId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).FindSendersByAccountId(ctx, req.(*FindSendersByAccountIdParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_FindSendersByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSendersByAddressParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).FindSendersByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/senderpb.Service/FindSendersByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).FindSendersByAddress(ctx, req.(*FindSendersByAddressParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "senderpb.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindSenderByAddressAndAccountID",
			Handler:    _Service_FindSenderByAddressAndAccountID_Handler,
		},
		{
			MethodName: "FindSendersByAccountId",
			Handler:    _Service_FindSendersByAccountId_Handler,
		},
		{
			MethodName: "FindSendersByAddress",
			Handler:    _Service_FindSendersByAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sender/rpc/senderpb/sender.proto",
}
