---
name: Backend
on:
  push:

jobs:
  build:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Code checkout
        uses: actions/checkout@v1
      - name: Setup dependencies
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8
      - name: Lint
        run: |
          cd backend
          ./runlint.sh

      - name: Unit Tests
        run: |
          cd backend
          ./runtest.sh

      - name: Integration Tests
        env:
          DOCKER_API_VERSION: 1.39
          RABBIT_EXCHANGE: webhook
          RABBIT_EXCHANGE_TYPE: direct  
          WEBHOOK_MIGRATION_ROOT:  file://../migration/sql
          INTEGRATION_TEST_FIXTURE_POSTGRES_USER: gnomock
          INTEGRATION_TEST_FIXTURE_POSTGRES_USER_PASSWORD: gnomick 
          INTEGRATION_TEST_FIXTURE_RABBITMQ_USER: gnomock
          INTEGRATION_TEST_FIXTURE_RABBITMQ_USER_PASSWORD: gnomick 
        run: |
          cd backend/webhook/integration_test
          go test -timeout 30s -tags integration

      - name: Build
        run: |
          cd backend
          go build -v github.com/burstsms/mtmo-tp/backend/...
